---
title: "practice"
output: html_document
---

```{r,echo=FALSE}
library(animation)
setwd("~/Documents/GitHub/linalg/")
```

```{r}
ani.options(interval = 0.2, nmax = 15)
## a coin would stand on the table?? just kidding :)
flip.coin(faces = c("Head", "Stand", "Tail"), type = "n", prob = c(0.45, 
  0.1, 0.45), col = c(1, 2, 4))
```

```{r}
rm(list=ls())
n<-4
x = sort(rnorm(n))
y = rnorm(n)
par(bg = "white")  # ensure the background color is white
plot(x, y, type = "n")

ani.record(reset = TRUE)  # clear history before recording

for (i in 1:n) {
  points(x[i], y[i], pch = 19, cex = 2)
  ani.record()  # record the current frame
}
oopts = ani.options(interval = 0.2)

saveHTML(ani.replay(), img.name = "record_plot")

```

```{r} 
#Edit
rm(list=ls())
par(bg = "white")  # ensure the background color is white
ani.record(reset=TRUE)

i1<-2
i2<-0
j1<-0
j2<-1
A <- matrix(c(i1,i2,j1,j2), 2, 2)



vec<-c(1,1)
add1<-c(-1,0.25)
add2<-c(2,0.75)

n<-20
for(j in 0:n){
  gradientmat<-matrix(c(1+j/n*(A[1,1]-1),j/n*A[2,1],j/n*A[1,2],1+j/n*(A[2,2]-1)), 2, 2)
  vecfinal<-gradientmat %*% vec
  add1final<-gradientmat %*% add1
  add2final<-gradientmat %*% add2

  plot(1,type = "n",xlim=c(-5,5), ylim=c(-5,5),xlab="title",main="f(a+b)=f(a)+f(b)")
  for (grid in -4:4){
  abline(h=grid,lty=2,col="gray")
  abline(v=grid,lty=2,col="gray")
  }
  arrows(0, 0, vecfinal[1], vecfinal[2], length = 0.1, angle = 30,code = 2,col="black")
  arrows(0, 0, add1final[1], add1final[2], length = 0.1, angle = 30,code = 2,col="green")
  arrows(add1final[1], add1final[2], add1final[1]+add2final[1], add1final[2]+add2final[2], length = 0.1, angle = 30,code = 2,col="blue")

  ani.record()
}



oopts = ani.options(interval = 0.05,loop=TRUE)
#ani.replay()
saveHTML(ani.replay(), img.name = "practicing", htmlfile = "animations.html")

```
```{r}
# Rotation
rm(list=ls())
par(bg = "white")  # ensure the background color is white
ani.record(reset=TRUE)

vec<-c(1,1)
add1<-c(-1,0.25)
add2<-c(2,0.75)

n <- 20
frames <- seq(0, 2*pi, by=2*pi/n)

for(j in frames){
  i1<- cos(j)
  i2<- sin(j)
  j1<- -sin(j)
  j2<- cos(j)
  gradientmat <- matrix(c(i1,i2,j1,j2), 2, 2)
  
  vecfinal<-gradientmat %*% vec
  add1final<-gradientmat %*% add1
  add2final<-gradientmat %*% add2

  plot(1,type = "n",xlim=c(-5,5), ylim=c(-5,5),xlab="title",main="f(a+b)=f(a)+f(b)")
  for (grid in -4:4){
  abline(h=grid,lty=2,col="gray")
  abline(v=grid,lty=2,col="gray")
  }
  arrows(0, 0, vecfinal[1], vecfinal[2], length = 0.1, angle = 30,code = 2,col="black")
  arrows(0, 0, add1final[1], add1final[2], length = 0.1, angle = 30,code = 2,col="green")
  arrows(add1final[1], add1final[2], add1final[1]+add2final[1], add1final[2]+add2final[2], length = 0.1, angle = 30,code = 2,col="blue")

  ani.record()
}



oopts = ani.options(interval = 0.1,loop=T)
# ani.replay()
saveHTML(ani.replay(), img.name = "rotation2", htmlfile = "animations.html")

```

```{r} 
#Creating a Grid
x<-vector()
for (b in (-4):4){
  y<-rep(b,9)
  x<-append(x,y,after=length(x))
  print(x)
}
w<-vector()
for (a in 1:9){
for (b in (-4):4){
  w<-append(w,b,after=length(x))
}
}
mat<-matrix(nrow=2,ncol=81)
mat[1,]<-x
mat[2,]<-w

#Plotting
par(bg = "white")  # ensure the background color is white
ani.record(reset=TRUE)

plot(1,type = "n",xlim=c(-5,5), ylim=c(-5,5),xlab="title",main="Dot Array")
 for (grid in -4:4){
  abline(h=grid,lty=2,col="gray")
  abline(v=grid,lty=2,col="gray")
 }
  cl<-colors()
  for (i in 1:81){
      points(mat[1,i],mat[2,i], pch = 19, col=cl[i])
  }


```

```{r}
#Dot Array
rm(list=ls())
par(bg = "white")  # ensure the background color is white
ani.record(reset=TRUE)

i1<-2
i2<-0
j1<-0
j2<-1
A <- matrix(c(i1,i2,j1,j2), 2, 2)




vec<-c(1,1)
add1<-c(-1,0.25)
add2<-c(2,0.75)

n<-20
for(j in 0:n){
  gradientmat<-matrix(c(1+j/n*(A[1,1]-1),j/n*A[2,1],j/n*A[1,2],1+j/n*(A[2,2]-1)), 2, 2)
  vecfinal<-gradientmat %*% vec
  add1final<-gradientmat %*% add1
  add2final<-gradientmat %*% add2

  plot(1,type = "n",xlim=c(-5,5), ylim=c(-5,5),xlab="title",main="f(a+b)=f(a)+f(b)")
  for (grid in -4:4){
  abline(h=grid,lty=2,col="gray")
  abline(v=grid,lty=2,col="gray")
  }
  arrows(0, 0, vecfinal[1], vecfinal[2], length = 0.1, angle = 30,code = 2,col="black")
  arrows(0, 0, add1final[1], add1final[2], length = 0.1, angle = 30,code = 2,col="green")
  arrows(add1final[1], add1final[2], add1final[1]+add2final[1], add1final[2]+add2final[2], length = 0.1, angle = 30,code = 2,col="blue")

  ani.record()
}



oopts = ani.options(interval = 0.05,loop=TRUE)
ani.replay()
saveHTML(ani.replay(), img.name = "practicing")

```


