---
title: "chapter1 exercises"
author: "Lijia Wang, Samantha Marglous"
date: "2020-06-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Chapter 1.3, Gaussian Elimination

```{r, echo=FALSE}
# Required packages
library(workflowr)
library(ramify)
setwd("~/Documents/GitHub/linalg/")
```


## Gaussian Elimination Function
Editing this to Perform LU Factorization
```{r}
# write a function for Gaussian Elimination on nx(n+1) matrix
ge <- function(matrix) {
  n <- dim(matrix)[1]
  # print(n)
  new_matrix <- matrix
  P_matrix<-diag(n)
  L_matrix<-diag(n)
  
  # row reduction
  for (ind in 1:(n-1)) {
     # print(paste("index is", ind))
     slice <- abs(new_matrix[ind:n,ind:(n+1)])
     # print(slice)
     # slice <- as.matrix(slice, byrow=TRUE)
     # print(slice)
     # print(argmax(slice,rows = FALSE))
     imax <- argmax(slice,rows = FALSE)[1]+(ind-1)
     # print(paste("imax=", imax))
    if (imax > ind){
      save <- new_matrix[ind,]
      new_matrix[ind,] <- new_matrix[imax,]
      new_matrix[imax,] <- save
      #Swapping Permutation Matrix Rows Too
      saveP <- P_matrix[ind,]
      P_matrix[ind,] <- P_matrix[imax,]
      P_matrix[imax,] <- saveP
      #Swapping L Matrix locations
      if (ind>1){
        saveL <- L_matrix[ind,1:(ind-1)]
        L_matrix[ind,1:(ind-1)] <- L_matrix[imax,1:(ind-1)]
        L_matrix[imax,1:(ind-1)] <-saveL
      }
    }
    for (row in (ind+1):n) {
      if (new_matrix[ind,ind] == 0){
        return('singularity matrix')
      } else {
      div <- new_matrix[row,ind] / new_matrix[ind,ind]
      #Fill in L matrix
      L_matrix[row,ind] <- div
      # print(div)
      tmp <- div * new_matrix[ind,]
      new_matrix[row,] <- new_matrix[row,] - tmp
      print('new_matrix')
      print(new_matrix)
      }
    }
  }

  # check last pivot is non-zero
  if (new_matrix[n,n] != 0) {
  # Back substitution
  ans <- rep(0, n)
  for (var in n:1) {
    ans[var] <- (new_matrix[var, n+1] - new_matrix[var, 1:n] %*% ans) / new_matrix[var, var]
  }
  } else {
    return("singular matrix")
  }
  return(list(ans,L_matrix,P_matrix,new_matrix))
}
```


## Some sample matrices from exercises in 1.3

```{r}
# 2x2, problem 3
mat1 <- matrix(c(2,-1,-4,5,6,0), 2, 3)
#      [,1] [,2] [,3]
# [1,]    2   -4    6
# [2,]   -1    5    0
ge(mat1)
# [1] 5 1

# 3x3, problem 10
mat2 <- matrix(c(2,4,0,3,7,-2,1,5,2,8,20,0), 3, 4)
#      [,1] [,2] [,3] [,4]
# [1,]    2    3    1    8
# [2,]    4    7    5   20
# [3,]    0   -2    2    0
ge(mat2)
# [1] 2 1 1

# 4x4, problem 20
mat3 <- matrix(c(2,1,0,0,1,2,1,0,0,1,2,1,0,0,1,2,0,0,0,5), 4,5)
#      [,1] [,2] [,3] [,4] [,5]
# [1,]    2    1    0    0    0
# [2,]    1    2    1    0    0
# [3,]    0    1    2    1    0
# [4,]    0    0    1    2    5
ge(mat3)
# [1] -1  2 -3  4

# 4x4, alt example: 
mat4 <- matrix(c(4,5,2,3,3,7,6,2,2,8,10,3,1,9,1,3,26,83,55,28), 4,5)
ge(mat4)

# singular matrix on page 13 (no solution)
mat5 <- matrix(c(1,2,4,1,2,4,1,5,8,5,6,7), 3,4)
#      [,1] [,2] [,3] [,4]
# [1,]    1    1    1    5
# [2,]    2    2    5    6
# [3,]    4    4    8    7
ge(mat5)

# singular matrix (inf solution)
mat6 <- matrix(c(1,2,4,1,2,4,1,4,8,5,6,12), 3,4)
#      [,1] [,2] [,3] [,4]
# [1,]    1    1    1    5
# [2,]    2    2    4    6
# [3,]    4    4    8    12
ge(mat6)
```


```{r}
# Saved Version From 7/1 write a function for Gaussian Elimination on nx(n+1) matrix
ge <- function(matrix) {
  n <- dim(matrix)[1]
  # print(n)
  new_matrix <- matrix
  
  # row reduction
  for (ind in 1:(n-1)) {
     # print(paste("index is", ind))
     slice <- abs(new_matrix[ind:n,ind:(n+1)])
     # print(slice)
     # slice <- as.matrix(slice, byrow=TRUE)
     # print(slice)
     # print(argmax(slice,rows = FALSE))
     imax <- argmax(slice,rows = FALSE)[1]+(ind-1)
     # print(paste("imax=", imax))
    if (imax > ind){
      save <- new_matrix[ind,]
      new_matrix[ind,] <- new_matrix[imax,]
      new_matrix[imax,] <- save
      # print(new_matrix)
    }
    for (row in (ind+1):n) {
      if (new_matrix[ind,ind] == 0){
        return('singularity matrix')
      } else {
      div <- new_matrix[row,ind] / new_matrix[ind,ind]
      # print(div)
      tmp <- div * new_matrix[ind,]
      new_matrix[row,] <- new_matrix[row,] - tmp
      # print(new_matrix)
      }
    }
  }

  # check last pivot is non-zero
  if (new_matrix[n,n] != 0) {
  # Back substitution
  ans <- rep(0, n)
  for (var in n:1) {
    ans[var] <- (new_matrix[var, n+1] - new_matrix[var, 1:n] %*% ans) / new_matrix[var, var]
  }
  } else {
    return("singular matrix")
  }
  return(ans)
}
```




```{r, eval=FALSE, echo=FALSE}
# scratch

for (row in 2:n) {
      div <- matrix[row,1] / matrix[1,1]
      print(paste("div", div))
      tmp <- div * matrix[1,]
      print(paste("tmp", tmp))
      new_matrix[row,] <- matrix[row,] - tmp
    }

# run code below to update site:
setwd('~/Documents/GitHub/linalg')
wflow_status()
wflow_publish(c("analysis/chapter1.Rmd", "analysis/index.Rmd"), "updated workflowr site")
wflow_git_push()
```


```{r}
#Saved Version 7/2
ge <- function(matrix) {
  n <- dim(matrix)[1]
  # print(n)
  new_matrix <- matrix
  P_matrix<-diag(n)
  L_matrix<-diag(n)
  
  # row reduction
  for (ind in 1:(n-1)) {
     # print(paste("index is", ind))
     slice <- abs(new_matrix[ind:n,ind:(n+1)])
     # print(slice)
     # slice <- as.matrix(slice, byrow=TRUE)
     # print(slice)
     # print(argmax(slice,rows = FALSE))
     imax <- argmax(slice,rows = FALSE)[1]+(ind-1)
     # print(paste("imax=", imax))
    if (imax > ind){
      save <- new_matrix[ind,]
      new_matrix[ind,] <- new_matrix[imax,]
      new_matrix[imax,] <- save
      #Swapping Permutation Matrix Rows Too
      saveP <- P_matrix[ind,]
      P_matrix[ind,] <- P_matrix[imax,]
      P_matrix[imax,] <- saveP
      #Swapping L Matrix locations
      if (ind>1){
        pos<-seq(1,(ind-1),1)
         for (position in pos){
          saveL <- L_matrix[ind,position]
          L_matrix[ind,position] <- L_matrix[imax,position]
          L_matrix[imax,position] <-saveL
        }
      }
    }
    for (row in (ind+1):n) {
      if (new_matrix[ind,ind] == 0){
        return('singularity matrix')
      } else {
      div <- new_matrix[row,ind] / new_matrix[ind,ind]
      #Fill in L matrix
      L_matrix[row,ind] <- div
      # print(div)
      tmp <- div * new_matrix[ind,]
      new_matrix[row,] <- new_matrix[row,] - tmp
      print('new_matrix')
      print(new_matrix)
      }
    }
  }

  # check last pivot is non-zero
  if (new_matrix[n,n] != 0) {
  # Back substitution
  ans <- rep(0, n)
  for (var in n:1) {
    ans[var] <- (new_matrix[var, n+1] - new_matrix[var, 1:n] %*% ans) / new_matrix[var, var]
  }
  } else {
    return("singular matrix")
  }
  return(list(ans,L_matrix,P_matrix,new_matrix))
}
```

